server:
    addr: ":5001"

token:
    issuer: "Auth Service"  # Must match issuer in the Registry config.
    expiration: 9000
    certificate: "/certs/mkt.registry.com.pem"
    key: "/certs/mkt.registry.com.key"

users:
    # Password is specified as a BCrypt hash. Use `htpasswd -nB USERNAME` to generate.
    "admin":
        password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin

acl:
    - match: {account: "admin"}
      actions: ["*"]
      comment: "Admin has full access to everything."